# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webrelation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_creature', to='webuser.Webuser'),
        ),
    ]
