# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webgroup',
            name='unread_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webuser',
            name='unread_num',
            field=models.IntegerField(default=0),
        ),
    ]
