# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webgroup',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='webuser',
            name='status',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
