# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('webuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_id', models.PositiveIntegerField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('feed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('-create_date',),
                'verbose_name': '\u041b\u0435\u043d\u0442\u0430',
                'verbose_name_plural': '\u041b\u0435\u043d\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='RootFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('edit_date', models.DateField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rootfeed_creature', to='webuser.Webuser')),
            ],
            options={
                'ordering': ('-create_date',),
                'verbose_name': '\u041b\u0435\u043d\u0442\u043e\u043a\u043e\u0440\u0435\u043d\u044c',
                'verbose_name_plural': '\u041b\u0435\u043d\u0442\u043e\u043a\u043e\u0440\u043d\u0438',
            },
        ),
    ]
