# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-create_date',),
                'verbose_name': '\u041b\u0435\u043d\u0442\u0430',
                'verbose_name_plural': '\u041b\u0435\u043d\u0442\u044b',
            },
        ),
    ]
