# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('edit_date', models.DateField(auto_now_add=True)),
                ('num_comments', models.IntegerField(default=0)),
                ('num_likes', models.IntegerField(default=0)),
                ('text', models.TextField(default='')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_creature', to='webuser.Webuser')),
            ],
            options={
                'ordering': ('-create_date',),
                'verbose_name': '\u041f\u043e\u0441\u0442',
                'verbose_name_plural': '\u041f\u043e\u0441\u0442\u044b',
            },
        ),
    ]
