# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpost', '0002_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='feed',
        ),
    ]
