# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='num_comments',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='num_likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
