# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcomment', '0002_auto_20161004_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='num_likes',
            field=models.IntegerField(default=0),
        ),
    ]
